spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/house?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: 123456
logging:
  file: house.log
  root: INFO
  level.org.springframework.web: INFO
  level.org.hibernate: ERROR
server:
  port: 8088